### ISSUE TITLE
게시판

### ISSUE THREAD

**Issue by psj24680** [psj24680/Everytime#4]
## 게시판

> 마크업
- [x] 게시판 제목
- [x] 글 입력창
- [x] 파일 업로드 버튼
- [x] 익명 버튼
- [x] 업로드 버튼
- [x] 게시글 목록

<hr>

> 기능 구현
- [x] File 업로드 / 이미지만 가능(jpg, jpeg, png, gif)
- [x] 익명 여부 확인 / 클릭 시 익명 버튼 이미지 변경
- [x] 게시글 불러오기
- [x] 게시글 클릭 시 상세화면으로 이동

**Comment by psj24680** [comment]
## 게시글 작성 시간 문제

``` YML
server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everytime?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
```

- 원인
postList를 model에 담아서 보낼 때 시간을 UTC로 보냈기 때문에 발생한 문제이다.

- 해결 방법
application.yml > datasource > url > serverTimezone=UTC를 지우면 해결된다.
